{% set name = "interproscan" %}
{% set version_minor = "86.0" %}
{% set version_major = "5.52" %}
{% set md5 = "b450ae120f6cfef2c146ca7fea9c178f" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version_major }}_{{ version_minor }}"

source:
  url: https://github.com/ebi-pf-team/interproscan/archive/{{ version_major }}-{{ version_minor }}.tar.gz
  md5: {{ md5 }}

build:
  number: 0

requirements:
  build:
    - openjdk >=11
    - {{ compiler('c') }}
    - maven >=3
  run:
    - python >=3
    - perl >=5.08
    - openjdk >=11

test:
  files:
    - test_proteins.fasta
    - test_nt_seqs.fasta
    - test_all_appl.fasta
  commands:
    - perl -version
    - python3 --version
    - java -version
    - interproscan.sh | grep XX
    - interproscan.sh | grep Xmx
    - interproscan.sh --version 
#    - interproscan.sh -i test_proteins.fasta -cpu 1 -f tsv -dp -appl sfld, hamap,prints,smart,pfam,pirsf,tigrfam,prositeprofiles,prositepatterns,gene3d,superfamily
#    - interproscan.sh -i test_proteins.fasta -cpu 1 -f tsv -appl sfld, hamap,prints,smart,pfam,pirsf,tigrfam,prositeprofiles,prositepatterns,gene3d,superfamily
#    - interproscan.sh -i test_nt_seqs.fasta -cpu 1 -t n -f tsv -dp -appl sfld, hamap,prints,smart,pfam,pirsf,tigrfam,prositeprofiles,prositepatterns,gene3d,superfamily
#    - interproscan.sh -i test_nt_seqs.fasta -cpu 1 -t n -f tsv -appl sfld, hamap,prints,smart,pfam,pirsf,tigrfam,prositeprofiles,prositepatterns,gene3d,superfamily
#    - interproscan.sh -i test_nt_seqs.fasta -cpu 1 -t n -f tsv,json,xml -appl pfam, pirsf
#    - interproscan.sh -i test_all_appl.fasta -cpu 1 -f tsv -dp -exclappl cdd
#    - interproscan.sh -i test_all_appl.fasta -cpu 1 -f tsv -dp -appl cdd

about:
  home: https://github.com/ebi-pf-team/interproscan
  license: GPLv3
  license_family: Apache
  license_file: LICENSE
  summary: InterPro integrates together predictive information about proteins function from a number of partner resources
  dev_url: https://github.com/ebi-pf-team/interproscan
