{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/AlBi-HHU/eXamine-stand-alone/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 642120e301dff596fcc779a54381fa6b62252744509ddb4bf57cbe4abb9c53a4

build:
  noarch: generic
  number: 0

requirements:
  host:
    - openjdk
    - maven
  run:
    - openjdk
    - python

test:
  commands:
    - examine --help

about:
  home: https://github.com/AlBi-HHU/eXamine-stand-alone
  license: GPL-2.0
  license_family: GPL
  summary: A graphical application to visually analyze network modules.
  dev_url: https://github.com/AlBi-HHU/eXamine-stand-alone
